# Generated by Django 4.0.2 on 2022-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('Photography', 'Photography'), ('Stylist ', 'Stylist'), ('Makeup ', 'Makeup'), ('Painting', 'Painting'), ('Graphic designer', 'Graphic designer'), ('Fashion designer', 'Fashion designer'), ('Modeling', 'Modeling')], max_length=150, null=True, verbose_name='Post Category'),
        ),
    ]
