# Generated by Django 4.0.2 on 2022-06-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_portfolio_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='category',
            new_name='portfolio_type',
        ),
    ]
