# Generated by Django 4.0.2 on 2022-06-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_category_portfolio_portfolio_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_type',
            field=models.CharField(choices=[('Photography', 'Photography'), ('Stylist ', 'Stylist'), ('Makeup ', 'Makeup'), ('Painting', 'Painting'), ('Graphic designer', 'Graphic designer'), ('Fashion designer', 'Fashion designer'), ('Modeling', 'Modeling')], max_length=150, null=True, verbose_name='Portfolio Category'),
        ),
    ]
